"""Generate `docs/reference/cli.md` from the live Typer app at `kuroi.cli:app`.

Runs as a standalone script. The output file is committed to git and refreshed
by `make docs-gen` (and verified in CI via `git diff --exit-code`).
"""

from __future__ import annotations

import sys
from pathlib import Path

import click
import typer

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from kuroi.cli import app  # noqa: E402
from typer.main import get_command  # noqa: E402


_BANNER = (
    "<!-- DO NOT EDIT — generated by docs/_scripts/gen_cli_reference.py. "
    "Run `make docs-gen` to refresh. -->\n"
)

_INTRO = """\
# CLI reference

Auto-generated from the live Typer app at `kuroi.cli:app`. Every option
and subcommand below comes straight from the source — if it doesn't match
`kuroi --help`, file a bug.
"""

_OUTPUT_PATH = _ROOT / "docs" / "reference" / "cli.md"

# Locked to 88 cols so the rendered help is wider than the typical 80-col
# default but still wraps cleanly inside a markdown code fence.
_HELP_COLUMNS = 88


def _disable_rich(typer_app: typer.Typer) -> None:
    """Recursively disable Typer's Rich-driven help formatter.

    Rich's output depends on terminal capabilities, locale, and Rich version,
    making the rendered help text non-deterministic across environments
    (e.g. local dev vs CI). Falling back to Click's built-in formatter gives
    plain text that's stable everywhere — required for the CI drift check.
    """
    typer_app.rich_markup_mode = None
    for grp in typer_app.registered_groups:
        if grp.typer_instance is not None:
            _disable_rich(grp.typer_instance)


def _help_block(cmd: click.Command, info_name: str) -> str:
    """Return the formatted `--help` output for a Click command, fenced as text."""
    ctx = click.Context(cmd, info_name=info_name, terminal_width=_HELP_COLUMNS)
    return f"```\n{cmd.get_help(ctx).rstrip()}\n```"


def render_cli_markdown() -> str:
    _disable_rich(app)
    root = get_command(app)
    sections: list[str] = [_BANNER, _INTRO, "", "## `kuroi`", "", _help_block(root, "kuroi"), ""]

    # Iterate subcommands in declaration order on the Typer app — TyperGroup
    # preserves registration order, so this is stable across Python versions.
    for name in root.commands:
        sub = root.commands[name]
        sections.append(f"## `kuroi {name}`")
        sections.append("")
        sections.append(_help_block(sub, f"kuroi {name}"))
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render_cli_markdown(), encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
