"""Generate `docs/reference/cli.md` from the live Typer app at `kuroi.cli:app`.

Runs as a standalone script. The output file is committed to git and refreshed
by `make docs-gen` (and verified in CI via `git diff --exit-code`).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from kuroi.cli import app  # noqa: E402
from typer.main import get_command  # noqa: E402


_BANNER = (
    "<!-- DO NOT EDIT — generated by docs/_scripts/gen_cli_reference.py. "
    "Run `make docs-gen` to refresh. -->\n"
)

_INTRO = """\
# CLI reference

Auto-generated from the live Typer app at `kuroi.cli:app`. Every option
and subcommand below comes straight from the source — if it doesn't match
`kuroi --help`, file a bug.
"""

_OUTPUT_PATH = _ROOT / "docs" / "reference" / "cli.md"

# Locked to 88 cols so the rendered help is wider than the typical 80-col
# default but still wraps cleanly inside a markdown code fence.
_HELP_COLUMNS = "88"


def _help_block(args: list[str]) -> str:
    """Capture `kuroi … --help` output via a subprocess.

    Typer's default rich_markup_mode routes help formatting through Rich's
    Console, which writes to stdout rather than populating Click's formatter
    buffer — so calling `cmd.get_help(ctx)` returns "". Spawning the actual
    `kuroi` CLI with NO_COLOR + a fixed COLUMNS gives deterministic plain
    text we can fence verbatim.
    """
    kuroi_bin = Path(sys.executable).parent / "kuroi"
    env = {**os.environ, "COLUMNS": _HELP_COLUMNS, "NO_COLOR": "1", "TERM": "dumb"}
    result = subprocess.run(
        [str(kuroi_bin), *args, "--help"],
        capture_output=True,
        text=True,
        env=env,
        check=True,
    )
    return f"```\n{result.stdout.rstrip()}\n```"


def render_cli_markdown() -> str:
    root = get_command(app)
    sections: list[str] = [_BANNER, _INTRO, "", "## `kuroi`", "", _help_block([]), ""]

    # Iterate subcommands in declaration order on the Typer app — TyperGroup
    # preserves registration order, so this is stable across Python versions.
    for name in root.commands:
        sections.append(f"## `kuroi {name}`")
        sections.append("")
        sections.append(_help_block([name]))
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render_cli_markdown(), encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
