"""Generate `docs/reference/cli.md` from the live Typer app at `kuroi.cli:app`.

Runs as a standalone script. The output file is committed to git and refreshed
by `make docs-gen` (and verified in CI via `git diff --exit-code`).
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from kuroi.cli import app  # noqa: E402
from typer.main import get_command  # noqa: E402


_BANNER = (
    "<!-- DO NOT EDIT — generated by docs/_scripts/gen_cli_reference.py. "
    "Run `make docs-gen` to refresh. -->\n"
)

_INTRO = """\
# CLI reference

Auto-generated from the live Typer app at `kuroi.cli:app`. Every option,
subcommand, and exit code below comes straight from the source — if it
doesn't match `kuroi --help`, file a bug.
"""

_OUTPUT_PATH = _ROOT / "docs" / "reference" / "cli.md"


def _help_block(cmd: click.Command, info_name: str) -> str:
    """Return the formatted `--help` output for a Click command, fenced as text."""
    ctx = click.Context(cmd, info_name=info_name, terminal_width=88)
    help_text = cmd.get_help(ctx).rstrip()
    return f"```\n{help_text}\n```"


def render_cli_markdown() -> str:
    root = get_command(app)
    assert isinstance(root, click.Group), "kuroi.cli:app must compile to a Click Group"

    sections: list[str] = [_BANNER, _INTRO, "", "## `kuroi`", "", _help_block(root, "kuroi"), ""]

    # Iterate subcommands in declaration order on the Typer app, not Click's dict
    # order — TyperGroup preserves registration order, so this is stable across
    # Python versions.
    for name in root.commands:
        sub = root.commands[name]
        sections.append(f"## `kuroi {name}`")
        sections.append("")
        sections.append(_help_block(sub, f"kuroi {name}"))
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render_cli_markdown(), encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
