"""Generate `docs/reference/rule-schema.md` from the kuroi.core.rules dataclasses.

Runs as a standalone script. The output file is committed to git and refreshed
by `make docs-gen` (and verified in CI via `git diff --exit-code`).
"""

from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from kuroi.core.rules import Category, RuleSet  # noqa: E402


_BANNER = (
    "<!-- DO NOT EDIT — generated by docs/_scripts/gen_rule_schema.py. "
    "Run `make docs-gen` to refresh. -->\n"
)

_INTRO = """\
# Rule schema

Auto-generated from the dataclasses in `kuroi.core.rules`. This page is
the source of truth for what a rule pack YAML file may contain. The
[Writing rule packs](../developer-guide/writing-rule-packs.md) guide
walks through using these fields end-to-end.
"""

_OUTPUT_PATH = _ROOT / "docs" / "reference" / "rule-schema.md"


def _format_type(t: object) -> str:
    return str(t).replace("typing.", "").replace("kuroi.core.", "")


def _field_table(cls: type) -> str:
    rows = ["| Field | Type | Description |", "| --- | --- | --- |"]
    for f in dataclasses.fields(cls):
        type_str = _format_type(f.type)
        desc = f.metadata.get("description", "") if f.metadata else ""
        rows.append(f"| `{f.name}` | `{type_str}` | {desc} |")
    return "\n".join(rows)


def render_schema_markdown() -> str:
    parts = [_BANNER, _INTRO, "", "## RuleSet", "", _field_table(RuleSet), ""]
    parts += ["## Category", "", _field_table(Category), ""]
    parts.append(
        "Refer to [`kuroi.core.rules`](api/rules.md) for the live "
        "definitions and helper functions (`load_rule_set`, "
        "`apply_regex_rules`)."
    )
    return "\n".join(parts) + "\n"


def main() -> None:
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render_schema_markdown(), encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
